baseURL = 'https://julhcam.eu/'
locale = 'en-gb'
title = 'JulHCam'
theme = "archie"
copyright = "© JulhCam"

# Colour palette https://coolors.co/7b2525-ba6a4c-fbfbee-bbd686-607456

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['$', '$'], ['\(', '\)']]

[params]
    mode="toggle" # color-mode → light,dark,toggle or auto
    useCDN=false
    mathjax = true # enable MathJax support
    katex = false # enable KaTeX support

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Publications"
url = "/publications"
weight = 2.5

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Search"
url = "/search"
weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/juliohc00/julhcam"

